import { useState } from 'react'
import Head from 'next/head'
import { Container, chakra } from '@chakra-ui/react'
import LlamaFactory from 'artifacts/contracts/LlamaFactory.sol/LlamaFactory.json'
import { ethers } from 'ethers';
import { useWeb3 } from 'context/AppContext'

const LLAMA_FACTORY_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3'

export default function Home() {
  const { provider } = useWeb3()
  const llamaFactory = new ethers.Contract(LLAMA_FACTORY_ADDRESS, LlamaFactory.abi, provider);

  const createRandomLlama = async (name: string) => {
    await llamaFactory.createRandomLlama(name)
  }

  // display llamas
  // create new llama on form submit with name
  // listen to llama created event to add a new llama

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.lg" mt="32">
        <chakra.h1 fontSize="4xl">Lets Get Started</chakra.h1>
      </Container>
    </div>
  )
}
